### ISSUE TITLE
Foreign constraint error when trying to execute an Insert query

### ISSUE THREAD

**Issue by gabrielgrover** [manyuanrong/deno_mysql#58]
mysql:5.7.30
deno: 1.0.5
deno_mysql: 2.2.0

I am trying to seed a test db.  I have a users table and credentials table.  The credentials table has a foreign key constraint on a field called userId.  In the following code I create a user record and use the id to insert a record in the credentials table.  When I run this query manually it works.  

```javascript

import { mysqlTestClient } from "./db/mysqlClient.ts";
import { bcrypt } from "./deps.ts";

const users = [
  {
    name: "john"
  }
]

const creds = [
  {
    email: "john@example.com",
    password: "password123"
  }
]

async function main() {

  console.log("\n\n************SEEDING TEST DB************\n\n");

  let insertedUserIds = [];
  for (const user of users) {
    const { name } = user;
    const { lastInsertId } = await mysqlTestClient.execute("INSERT INTO users(name) values(?)", [name]);
    insertedUserIds.push(lastInsertId);
  }

  for (let i = 0; i < creds.length; i++) {
    const userId = insertedUserIds[i];
    const { email, password } = creds[i];
    const salt = bcrypt.genSaltSync(10);
    const hashPW = bcrypt.hashSync(password, salt);
    await mysqlTestClient.execute("INSERT INTO credentials(email, password, userId) values(email, password, userId)", [
      email,
      hashPW,
      userId
    ]);
  }
}
``` 

When i run the above code I get the following error

```
error: Uncaught Error: Cannot add or update a child row: a foreign key constraint fails (`every_menu`.`credentials`, CONSTRAINT `credentials_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`id`))
          throw new Error(error.message);
                ^
    at Connection.nextPacket (https://deno.land/x/mysql@2.2.0/src/connection.ts:95:17)
    at async Connection.execute (https://deno.land/x/mysql@2.2.0/src/connection.ts:162:19)
    at async https://deno.land/x/mysql@2.2.0/src/client.ts:101:14
    at async Client.useConnection (https://deno.land/x/mysql@2.2.0/src/client.ts:111:22)
    at async Client.execute (https://deno.land/x/mysql@2.2.0/src/client.ts:100:12)
    at async main (file:///Users/gabrielgrover/thrive-market/deno-demo/seedTestDb.ts:59:5)
```

Here are the schemas for both tables 

```
users (
    id int(11) NOT NULL AUTO_INCREMENT,
    name varchar(255) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

credentials (
    id int(11) NOT NULL AUTO_INCREMENT,
    email varchar(255) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    userId int(11) NOT NULL UNIQUE,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (userId) REFERENCES every_menu.users(id)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
```

Not too sure what is happening.

**Comment by gabrielgrover** [comment]
I found the issue.  It was an error on my part.  The query should be

"INSERT INTO credentials(email, password, userId) values(?, ?, ?)"

instead of 

""INSERT INTO credentials(email, password, userId) values(email, password, userId)""
